server:
  port: 1210

logging:
  level:
    root: INFO
    com.calcpro: DEBUG

spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/flow-master_db_v1
    username: user
    password: 123456
  jpa:
    hibernate:
      ddl-auto: create-drop #update
    show-sql: true
  liquibase:
    change-log: classpath:/liquibase/changelog-master.yml
